config/routes.rb
# -*- encoding : utf-8 -*-
Rails.application.routes.draw do

  #api/v1
  get 'api/v1/restart_appium_for_simulator' => 'api/v1#restart_appium_for_simulator'
  get 'api/v1/restart_appium_for_mobile' => 'api/v1#restart_appium_for_mobile'
  get 'api/v1/restart_appium_for_tablet' => 'api/v1#restart_appium_for_tablet'

  get 'api/v1/job_finished' => 'api/v1#job_finished'

  post 'api/v1/job_unschedule' => 'api/v1#job_unschedule'

  #data
  get 'data/behavior.json' => 'data#behavior'
  get 'data/graph.json' => 'data#graph'
  get 'data/xunit.json' => 'data#xunit'
  get 'data/report.json' => 'data#report'
  get 'data/environment.json' => 'data#environment'
  get 'data/defects.json' => 'data#defects'
  get 'data/:id-testcase.json' => 'data#testcase'

  get 'testrun/:id' => 'testrun#index', as: :testrun
  post 'testrun/:id/schedule' => 'testrun#schedule', as: :testrun_schedule
  post 'testrun/:id/unschedule' => 'testrun#unschedule', as: :testrun_unschedule
  post 'testrun/:id/schedule_failed_or_pending' => 'testrun#schedule_failed_or_pending', as: :testrun_schedule_failed_or_pending

  get 'android' => 'android#index'
  get 'api' => 'api#index'

  get 'ios' => 'ios#index'
  post 'upload' => 'upload#upload'

  get 'messaging' => 'step#send_message'

  root :to => 'root#index'
end

app/controllers/ios_controller.rb
# -*- encoding : utf-8 -*-
class IosController < ApplicationController

  def index
    @testruns_simulator_ios_8_x = Testrun.where(type: TestrunType.simulator_ios_8_x, disabled: false).order(:sort).decorate
    @testruns_simulator_ios_9_x = Testrun.where(type: TestrunType.simulator_ios_9_x, disabled: false).order(:sort).decorate

    @testruns_device_ios_8_x = []
    @testruns_device_ios_9_x = []

    @testruns_ios = Testrun.where(type: [TestrunType.simulator_ios_8_x, TestrunType.simulator_ios_9_x], disabled: false)

    @expected = [1, 2, 3].to_xml
    @got = [1, 2, 3, 4].to_xml

    @jobs = JenkinsJob.where(status: [JobStatus.scheduled, JobStatus.running]).order(:created_at).decorate

    @steps = AppstoreCheck.showing_steps
  end

end

app/views/ios/appstore/_index.html.erb
<div class="row">
  <div class="col-md-12">
    <%= react_component('UploadForm', {version: '1.0.27', upload_url: upload_path}) %>
  </div>
</div>

<br/>

<div class="row">
  <div class="col-md-12">
    <%= react_component('CheckTable', {
                                            checks: @steps.map { |step| {id: step.id, name: step.name, command: step.command} },
                                            live_url: messaging_path
                                    }) %>
  </div>

</div>

<div class="row">
  <div class="col-md-12">
    <%= react_component('CheckResult') %>
  </div>
</div>