config/routes.rb
# -*- encoding : utf-8 -*-
Rails.application.routes.draw do

  #api/v1
  get 'api/v1/restart_appium_for_simulator' => 'api/v1#restart_appium_for_simulator'
  get 'api/v1/restart_appium_for_mobile' => 'api/v1#restart_appium_for_mobile'
  get 'api/v1/restart_appium_for_tablet' => 'api/v1#restart_appium_for_tablet'

  get 'api/v1/job_finished' => 'api/v1#job_finished'

  post 'api/v1/job_unschedule' => 'api/v1#job_unschedule'

  #data
  get 'data/behavior.json' => 'data#behavior'
  get 'data/graph.json' => 'data#graph'
  get 'data/xunit.json' => 'data#xunit'
  get 'data/report.json' => 'data#report'
  get 'data/environment.json' => 'data#environment'
  get 'data/defects.json' => 'data#defects'
  get 'data/:id-testcase.json' => 'data#testcase'

  get 'testrun/:id' => 'testrun#index', as: :testrun
  post 'testrun/:id/schedule' => 'testrun#schedule', as: :testrun_schedule
  post 'testrun/:id/unschedule' => 'testrun#unschedule', as: :testrun_unschedule
  post 'testrun/:id/schedule_failed_or_pending' => 'testrun#schedule_failed_or_pending', as: :testrun_schedule_failed_or_pending

  get 'android' => 'android#index'
  get 'api' => 'api#index'

  get 'ios' => 'ios#index'
  post 'upload' => 'upload#upload'

  get 'messaging' => 'step#send_message'

  root :to => 'root#index'
end

app/views/shared/_badges.html.erb
<div class="row">

  <div class="col-lg-4 col-md-4">
    <% if failed_scenarios(testruns) == 0 and total_scenarios(testruns) > 0 %>
        <div class="panel panel-success">
    <% else %>
        <div class="panel panel-danger">
    <% end %>

    <div class="panel-heading">
      <div class="row">

        <div class="col-xs-6">
          <h5>Failed scenarios</h5>
        </div>

        <div class="col-xs-6 text-right">
          <h4>
            <%= failed_scenarios(testruns) %>
            /
            <%= total_scenarios(testruns) %>
          </h4>
        </div>

      </div>
    </div>

    </div>
    </div>

    <div class="col-lg-4 col-md-4">
      <div class="panel panel-info">
        <div class="panel-heading">
          <div class="row">

            <div class="col-xs-6">
              <h5>Duration</h5>
            </div>

            <div class="col-xs-6 text-right">
              <h4><%= total_duration(testruns) %></h4>
            </div>

          </div>
        </div>

      </div>
    </div>

    <div class="col-lg-4 col-md-4">
      <div class="panel panel-default">
        <div class="panel-heading">
          <div class="row">

            <div class="col-xs-10">
              <h4>iOS infrastructure is available for last 5 minutes</h4>
            </div>

            <div class="col-xs-2 text-right">

              <% if Infrastructure.available_last_5_minutes? %>
                  <h4>YES</h4>
              <% else %>
                  <h4>NO</h4>
              <% end %>

            </div>

          </div>
        </div>

      </div>
    </div>

  </div>

app/views/shared/_sidebar.html.erb
<ul class="nav nav-sidebar">
  <% if active.downcase == 'ios' %>
      <li class="active">
  <% else %>
      <li>
  <% end %>
  <%= link_to 'iOS', ios_path %>
  </li>

  <% if active.downcase == 'android' %>
      <li class="active">
  <% else %>
      <li>
  <% end %>
  <%= link_to 'Android', android_path %>
  </li>

  <% if active.downcase == 'api' %>
      <li class="active">
  <% else %>
      <li>
  <% end %>

  <%= link_to 'API', api_path %>
  </li>
</ul>

app/views/shared/_table.html.erb
<table class="table table-striped">
  <thead>
  <tr>
    <th>Testrun</th>
    <th>Last run at</th>
    <th>Last duration</th>
    <th>Status</th>
    <th>Running now</th>
    <th>Actions</th>
  </tr>
  </thead>
  <tbody>
  <% testruns.each do |testrun| %>
      <tr>
        <td style="vertical-align: middle; width: 90px">
          <%= testrun.details %>
        </td>
        <td style="vertical-align: middle; width: 150px;">
          <%= testrun.last_run_at %>
        </td>
        <td style="vertical-align: middle; width: 175px;">
          <%= testrun.duration %>
        </td>
        <td style="vertical-align: middle; width: 125px;">
          <%= testrun.status %>
        </td>
        <td style="vertical-align: middle; width: 120px;">
          <%= testrun.running_now %>
        </td>

        <td style="vertical-align: middle; width: 125px;">
          <%= testrun.action_button %>
        </td>
      </tr>
  <% end %>

  <tr>
    <td>
      Total
    </td>
    <td></td>
    <td><%= total_duration(testruns) %></td>
    <td></td>
    <td></td>
    <td></td>
  </tr>

  </tbody>
</table>